# Colors
C_RESET="$(tput sgr0)"
C_BLACK="$(tput setaf 0)"
C_DRED="$(tput setaf 1)"
C_DGREEN="$(tput setaf 2)"
C_DYELLOW="$(tput setaf 3)"
C_DBLUE="$(tput setaf 4)"
C_DMAGENTA="$(tput setaf 5)"
C_DCYAN="$(tput setaf 6)"
C_DWHITE="$(tput setaf 7)"
C_GRAY="$(tput setaf 8)"
C_LRED="$(tput setaf 9)"
C_LGREEN="$(tput setaf 10)"
C_LYELLOW="$(tput setaf 11)"
C_LBLUE="$(tput setaf 12)"
C_LMAGENTA="$(tput setaf 13)"
C_LCYAN="$(tput setaf 14)"
C_WHITE="$(tput setaf 15)"

